spring:
  profiles:
    active: test
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2

  h2:
    console.enabled: true


game:
  pokemon:
    pokeapi-list: https://pokeapi.co/api/v2/pokemon?offset=1&limit=50
    number-round:  3
    type-attack-normal: [1,10,1]
    type-attack-special: [2,15,5]